{*
 * @version    $Id: template.phtml 2 2009-07-13 20:58:52Z david@grudl.com $
 * @param Paginator $paginator
 * @param array     $steps
 *}

{if $paginator->pageCount > 1}
<div class="paginator clearfix">
	{if $paginator->isFirst()}
	<span class="prev">« Naspäť</span>
	{else}
	<a class="prev" href="{link this, 'page' => $paginator->page - 1}">« Naspäť</a>
	{/if}

    <div class="pages">
	{foreach $steps as $step}
	{if $step == $paginator->page}
		<span class="current">{$step}</span>
	{else}
		<a href="{link this, 'page' => $step}">{$step}</a>
	{/if}
	{if $iterator->nextValue > $step + 1}<span>…</span>{/if}
	{/foreach}
    </div>

	{if $paginator->isLast()}
	<span class="next">Ďalej »</span>
	{else}
	<a class="next" href="{link this, 'page' => $paginator->page + 1}">Ďalej »</a>
	{/if}
</div>
{/if}
